project_id = "wofpxloehneavpoiqpal"

[functions.incoming-call]
verify_jwt = false

[functions.ivr-handler]
verify_jwt = false

[functions.call-twiml]
verify_jwt = false

[functions.call-events]
verify_jwt = false

[functions.receive-message]
verify_jwt = false

[functions.send-message]
verify_jwt = false

[functions.voicemail-twiml]
verify_jwt = false

[functions.voicemail-callback]
verify_jwt = false

[functions.voicemail-transcription]
verify_jwt = false

[functions.end-conference]
verify_jwt = false

[functions.pause-recording]
verify_jwt = false

[functions.resume-recording]
verify_jwt = false

[functions.transcribe-recording]
verify_jwt = false

[functions.preview-voice]
verify_jwt = false

[functions.transfer-call]
verify_jwt = false

[functions.cancel-call]
verify_jwt = false

[functions.call-hangup]
verify_jwt = false

[functions.hold-call]
verify_jwt = false

[functions.send-to-voicemail]
verify_jwt = false

[functions.start-recording]
verify_jwt = false

[functions.telnyx-incoming-call]
verify_jwt = false

[functions.telnyx-call-events]
verify_jwt = false

[functions.telnyx-make-call]
verify_jwt = false

[functions.telnyx-outbound-texml]
verify_jwt = false

[functions.telnyx-generate-token]
verify_jwt = false

[functions.telnyx-voicemail-twiml]
verify_jwt = false

[functions.telnyx-voicemail-callback]
verify_jwt = false

[functions.telnyx-start-recording]
verify_jwt = false

[functions.telnyx-transfer-call]
verify_jwt = false

[functions.telnyx-transfer-texml]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.telnyx-hold-music]
verify_jwt = false

[functions.telnyx-pickup-call]
verify_jwt = false

[functions.telnyx-hangup-call]
verify_jwt = false

[functions.telnyx-pause-recording]
verify_jwt = false

[functions.telnyx-resume-recording]
verify_jwt = false

[functions.generate-token]
verify_jwt = false

[functions.sync-telnyx-numbers]
verify_jwt = false

[functions.sync-twilio-numbers]
verify_jwt = false

[functions.admin-assign-phone]
verify_jwt = false

[functions.admin-department]
verify_jwt = false

[functions.admin-user]
verify_jwt = false

[functions.telnyx-debug-credentials]
verify_jwt = false

[functions.telnyx-send-to-voicemail]
verify_jwt = false

[functions.telnyx-save-recording]
verify_jwt = false

[functions.update-call-status]
verify_jwt = false

[functions.telnyx-ivr-gather]
verify_jwt = false

[functions.admin-ivr]
verify_jwt = false

[functions.admin-subscription]
verify_jwt = false

[functions.stripe-webhooks]
verify_jwt = false

[functions.verify-queue-calls]
verify_jwt = false
